spring.config.import=optional:file:.env[.properties]

spring.application.name=AuthUserBackend

spring.output.ansi.enabled=always

# H2 CONFIGURATION
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# MAIN DATABASE CONFIGURATION
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT CONFIGURATION
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8080,http://localhost:5173}
